first_app/urls.py
from django.urls import path
from . import views

app_name = 'first_app'
urlpatterns = [
    path('', views.app_index, name='app_index'),
    path('home/', views.home, name='home'),
    path('form/', views.forms, name='form'),
    path('testform/', views.test_forms, name='testforms'),
    path('handleform/', views.handle_forms, name='handleform'),
    path('modifyuser/', views.modify_user, name='modifyuser')
]

first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', views.index, name='index'),
    path('firstapp/', include('first_app.urls'))
    # path('<int:num>/', views.odd_or_even, name='odd_or_even'),
    # path('', RedirectView.as_view(url='hello/')),
    # path('', RedirectView.as_view(url='firstapp/', permanent=True)),
    # path('<age>/', views.show_age, name='show_age'),
]

first_app/models.py
from django.db import models
from datetime import date as dt

# Create your models here.


class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField(default=dt.today)
    count = models.IntegerField(default=0)

    def __str__(self):
        return str(self.date)

first_app/forms.py
from django import forms


class SearchForm(forms.Form):
    q = forms.CharField()


class TestForm(forms.Form):
    text = forms.CharField(min_length=7)
    boolean = forms.BooleanField()
    integer = forms.IntegerField()
    email = forms.EmailField()

    def clean_integer(self):
        integer = self.cleaned_data.get('integer')
        if integer < 10:
            raise forms.ValidationError("The integer must be greater than 10.")
        return integer

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Topic
from .forms import SearchForm, TestForm
from django.contrib.auth.models import User
from django.db import IntegrityError

# Create your views here.


def index(request):
    return HttpResponse("Hello World!")


def app_index(request):
    favorite_book = {'Raymond': "The Kite Runner", 'Emma': "A Thousand Splendid Suns",
                     'Denise': "The Great Gatsby", 'Austin': "Holly Lover"}
    return render(request, 'first_app/index.html', context=favorite_book)
    # return HttpResponse("Hello from my first app!")


def home(request):
    try:
        # user = User.objects.create_user(
        #     username="Kotomi", email="123@gmail.com", password="123")
        # user.save()
        topic = Topic.objects.create(top_name="Songs")
        topic.save()
    except IntegrityError as e:
        print(e)
    return HttpResponse("Welcome to the home page of my first app!")


def show_age(request, age):
    return HttpResponse(f"I am {age} years old.")


def odd_or_even(request, num):
    if (num % 2 == 0):
        result = "even"
    else:
        result = "odd"
    return HttpResponse(f"{num} is an {result} number!")


def forms(request):
    form = SearchForm()
    return render(request, 'first_app/form.html', {'form': form})


def test_forms(request):
    test_form = TestForm()
    return render(request, "first_app/form.html", {'form': test_form})


def handle_forms(request):
    form = TestForm(request.POST or None)
    data = "None"
    text = None
    if form.is_valid():
        data = form.cleaned_data
        text = form.cleaned_data.get("text")
    return render(request, 'first_app/form.html', {'form': form, 'data': data, 'text': text})


def modify_user(request):
    try:
        user = User.objects.get(username="Kotomi")
        user.email = "456@gmail.com"
        user.save()
    except IntegrityError as e:
        print(e)
    return HttpResponse("Welcome to modify user page!")

templates/first_app/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forms</title>
</head>
<body>
    <!-- <form method="GET" action="https://google.com">
        {{form}}
        <input type="submit" value="Search">
    </form> -->

    <form method="POST" action="">{% csrf_token %}
        {{form}}
        <input type="submit" value="Search">
    </form>

    Data: {{data}}
    <br>
    Text: {{text}}
</body>
</html>

templates/first_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First Application</title>
</head>
<body>
    <h1>Hello this is index.html!</h1>
    <h2>Hi, this is my picture!</h2>
    <img src="{% static 'first_app/images/me.jpg' %}" alt="Uh oh, didn't show!">

    <h2>This book is: {{Austin}}</h2>
    <a href="{% url 'first_app:home' %}"> My Home</a>
</body>
</html>